### ISSUE TITLE
이경엽 1일차 과제

### ISSUE THREAD

**Issue by kyupkyup** [ai-creatv/algorithm_nklcb1#1]
코드 링크입니다!
![레벨1](https://user-images.githubusercontent.com/23183045/111965631-4a3f6f00-8b39-11eb-9976-3c4fc4843352.png)

https://github.com/kyupkyup/algorithm_practice/tree/master/%ED%8C%A8%EC%8A%A4%ED%8A%B8%EC%BA%A0%ED%8D%BC%EC%8A%A4/1%EC%9D%BC%EC%B0%A8

**Comment by ai-creatv** [comment]
깔끔하게 잘 구현해 주셨습니다 :) 수고하셨습니다!

코멘트를 하나 드리자면, 파이썬 파일은 숫자로 시작하지 않는 것이 좋습니다 :)

숫자로 시작하는 경우 해당 파일은 모듈로 import를 하지 못하기 때문에, 습관을 들여두시는게 좋아요~
