### ISSUE TITLE
이경엽 1일차 과제 추가 풀이

### ISSUE THREAD

**Issue by kyupkyup** [ai-creatv/algorithm_nklcb1#12]
코드

https://github.com/kyupkyup/algorithm_practice/tree/master/%ED%8C%A8%EC%8A%A4%ED%8A%B8%EC%BA%A0%ED%8D%BC%EC%8A%A4/1%EC%9D%BC%EC%B0%A8%20%EC%9E%AC%ED%92%80%EC%9D%B4

사진
![1일차 과제](https://user-images.githubusercontent.com/23183045/111987234-4c61f780-8b52-11eb-8ac4-a33c1a06ac3a.PNG)

**Comment by ai-creatv** [comment]
깔끔하게 잘 구현해 주셨습니다 :) 수고하셨습니다!

코멘트를 하나 드리자면, 파이썬 파일은 숫자로 시작하지 않는 것이 좋습니다 :)

숫자로 시작하는 경우 해당 파일은 모듈로 import를 하지 못하기 때문에, 습관을 들여두시는게 좋아요~
