### ISSUE TITLE
김성휘 2일차 과제입니다.

### ISSUE THREAD

**Issue by kiiwoom8** [ai-creatv/algorithm_nklcb1#21]
https://github.com/kiiwoom8/test

수고많으셨어용~

**Comment by ai-creatv** [comment]
1. ArrayList의 is_empty 구현이 거꾸로 되었네요! 그리고 C계열과 달리 if 뒤에 보통 괄호는 쓰지 않습니다 :)
2. ArrayList의 capacity가 부족한 경우에 대해서 고려가 되어 있지 않네요. 이 부분 구현해 보시는 것을 추천드립니다 :)
3. index가 벗어나는 경우에 대한 예외처리도 습관처럼 해 주시면 좋습니다!
4. linked list의 currentValue, previousValue의 경우, currentNode, previousNode로 바꿔주시는 것이 좋을 것 같습니다(value가 아닌 node를 참조하기 때문이지요!). 또한, 이 변수들은 인스턴스 변수로 할 필요는 없기 때문에, 로컬변수로(self.제거)구현해 주시는 편이 더 좋습니다.
5. for문과 if~elif문이 딱 붙어있어서 가독성이 떨어지는 것 같네요! for문과 if문은 한칸 띄어 주시면 훨씬 가독성이 좋아질 것 같습니다 :)

수고하셨습니다 :)

**Comment by kiiwoom8** [comment]
지금보니 너무 부끄럽네요 ㅋㅋㅋ 감사합니다 잘하겠습니다!
-----Original Message-----
