### ISSUE TITLE
윤다은 2일차 과제 제출합니다.

### ISSUE THREAD

**Issue by YunPC** [ai-creatv/algorithm_nklcb1#24]
https://github.com/YunPC/algorithm_homework/tree/main/homework2

**Comment by ai-creatv** [comment]
- 몇몇 메소드 구현에 들여쓰기가 너무 많이 들어가네요! 예외처리 후에 return을 하셔서 else를 최대한 제거하시면 들여쓰기가 줄어듭니다. 들여쓰기는 코드의 '복잡도'를 높이기 때문에 최소화 하는 것이 좋습니다.
- SLL에서 인스턴스 메소드 호출을 클래스명으로 해 주셨는데, 보통은 self.is_empty()처럼 self 변수로 접근하는 것이 좋습니다. 클래스명으로 접근하는 것은 클래스 메소드나 스태틱 메소드의 경우에만 특별히 사용하며, 이것은 @classmethod나 @staticmethod로 데코레이션하여 사용합니다.

수고하셨습니다! :)
