### ISSUE TITLE
김영종 2일차 과제 입니다.

### ISSUE THREAD

**Issue by toryjkim** [ai-creatv/algorithm_nklcb1#28]
https://github.com/toryjkim/fastCampus/tree/main/homework/%EC%8B%A0%EC%A0%9C%EC%9A%A9_%EA%B0%95%EC%82%AC%EB%8B%98/2%EC%9D%BC%EC%B0%A8

**Comment by ai-creatv** [comment]
- ArrayList의 insert에서 배열 증가시 복사가 2번 이루어지는 영역이 있는 점 확인해주세요.
- 변수명은 snake_case나 camelCase 둘중 하나로 통일하시는 것이 좋습니다 :)
- elif나 else를 많이 사용할 경우, 불필요하게 들여쓰기가 많이 들어갑니다. return을 활용하셔서 들여쓰기를 줄이시는 것을 추천드립니다. 들여쓰기는 코드의 복잡도에 해당하기 때문에, 최소화하는 것이 좋습니다.

수고하셨습니다! :)
