### ISSUE TITLE
허재혁 1일차 과제

### ISSUE THREAD

**Issue by Jack2ee-dev** [ai-creatv/algorithm_nklcb1#3]
네카라쿠배 자료구조/알고리즘 1일차 과제 제출합니다.

**github**: https://github.com/Jack2ee-dev/NKLCB_homework/tree/master/programmersSkillCheckLevel1

**이미지**
<img width="1680" alt="스크린샷 2021-03-22 오후 6 08 53" src="https://user-images.githubusercontent.com/63090191/111968244-4c56fd00-8b3c-11eb-9d41-14ccfa1da5d8.png">

**Comment by ai-creatv** [comment]
가독성 좋게 잘 구현해 주셨네요! 수고하셨습니다 :)
