### ISSUE TITLE
허재혁 3일차 과제 제출합니다

### ISSUE THREAD

**Issue by Jack2ee-dev** [ai-creatv/algorithm_nklcb1#30]
3일차 linear_queue와 linked_queue 구현 과제 제출합니다.

* github url: https://github.com/Jack2ee-dev/NKLCB_homework/tree/master/queue

**Comment by ai-creatv** [comment]
- linear queue의 peek에서 front가 증가하면 안되는 부분 확인해주세요 :)

수고하셨습니다!

**Comment by Jack2ee-dev** [comment]
peek()의 로직은 이해했는데 테스트를 많이 안해봐서 오류가 있었습니다.
확인해주셔서 감사합니다 :)
