### ISSUE TITLE
김성휘 3일차 과제입니다

### ISSUE THREAD

**Issue by kiiwoom8** [ai-creatv/algorithm_nklcb1#35]
https://github.com/kiiwoom8/test

고생 많으셨습니다!

**Comment by ai-creatv** [comment]
- LinearQueue의 peek에서 underflow가 발생할 수 있는 점 확인해주세요 :)
- LinkedQueue의 경우 put을 구현할 때 tail에서 곧바로 입력이 가능한 점 확인해 주세요!
수고하셨습니다 :)
