### ISSUE TITLE
이경엽 3일차 과제입니다~

### ISSUE THREAD

**Issue by kyupkyup** [ai-creatv/algorithm_nklcb1#38]
https://github.com/kyupkyup/algorithm_practice/tree/master/%ED%8C%A8%EC%8A%A4%ED%8A%B8%EC%BA%A0%ED%8D%BC%EC%8A%A4/3%EC%9D%BC%EC%B0%A8

**Comment by ai-creatv** [comment]
- LinkedQueue의 구현에서, 가능하다면 super()보다는 self가 선호되는 점(다형성에 의해) 확인해 주세요 :)
수고하셨습니다!
