### ISSUE TITLE
차유림 3일차 과제입니다

### ISSUE THREAD

**Issue by chachacha912** [ai-creatv/algorithm_nklcb1#42]
https://github.com/chachacha912/algorithm_nklcb1/tree/main/0324/queue

**Comment by ai-creatv** [comment]
아주 깔끔하게 잘 구현해 주셨습니다 :) 수고하셨습니다!

**Comment by ai-creatv** [comment]
def peek(self):
        if self.head is None and self.tail is None:
            return None # Underflow
        else:
            return self.head.value

위 코드에서는 and self.tail is None이 없는 편이 더 좋습니다. head가 None이고 tail이 None이라면, else문에서 오류가 발생하기 때문이지요!

실제로는 head와 tail이 함께 None이기 때문에 위와 같은 상황이 발생하지는 않지만, 이와 같이 '위태해 보이는 코드'보다는 확실히 문제가 되지 않는 코드가 더 좋습니다 :)
