### ISSUE TITLE
오재원 1일차 과제

### ISSUE THREAD

**Issue by ProgWon** [ai-creatv/algorithm_nklcb1#6]
https://github.com/ProgWon/FastCampusAlgorithm/tree/main/Homework%231

**Comment by ai-creatv** [comment]
가독성 좋게, 깔끔하게 잘 구현해 주셨네요! 수고하셨습니다 :)

다만 문제 스크린샷을 올리신 것은 저작권 문제가 될 수 있으니, 삭제해 주세요!

보통은 출처를 밝혀서 문제를 기재하셔도 되지만, 스킬체크의 경우 테스트에 사용되는 것이기 때문에 삭제하는 것을 추천드립니다 :)
