### ISSUE TITLE
김성휘 1일차 과제입니다.

### ISSUE THREAD

**Issue by kiiwoom8** [ai-creatv/algorithm_nklcb1#7]
![캡처](https://user-images.githubusercontent.com/57394396/111974918-56302e80-8b43-11eb-9e7f-3a0bd8ec9e73.PNG)

https://github.com/kiiwoom8/test

**Comment by ai-creatv** [comment]
깔끔하게 잘 구현해 주셨습니다! :)

1번 문제의 변수 i와 2번 문제의 변수 a, b는 더 적절한 이름을 쓰면 좋을 것 같습니다.

i -> count
a -> r (rows)
b -> c (columns)

정도가 보통 사용하는 변수명입니다 :)

**Comment by kiiwoom8** [comment]
​
감사합니다!! 다음번부터 해당사항 적용하여 구현하겠습니다. 오늘도 좋은 하루 되세요 ㅎㅎ
​
-----Original Message-----
