### ISSUE TITLE
안승재 1일차 과제입니다.

### ISSUE THREAD

**Issue by getState** [ai-creatv/algorithm_nklcb1#8]
![image](https://user-images.githubusercontent.com/49035066/111975585-203f7a00-8b44-11eb-81a1-fd97f84d4d0e.png)

https://github.com/getState/nklcb_algorithm/tree/main/Assignment1

**Comment by ai-creatv** [comment]
잘 구현해 주셨습니다! :)

- 1번 문제에서 배열의 원소가 없는 경우를 먼저 처리해 주셔야 합니다. 지금은 arr의 길이가 0인 경우 arr[0]으로 원소에 접근하려고 시도하면서 오류가 발생하게 됩니다.

- 2번 문제에서 set을 이용하셨는데, 문제에서 중복되는 수가 없는 조건이라면 이것이 맞고, 관련 조건이 없다면 set이 아닌 list를 이용하셔야 맞는 점 참고해주세요 :)

수고하셨습니다!
